apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: backend-ingress
 annotations:
   kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
 rules:
 - host: -.us-south.containers.appdomain.cloud
   http:
     paths:
     - path: /
       backend:
         serviceName: karsajobs-service
         servicePort: 8080
