apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ibm-storage
 labels:
   billingType: "hourly"
   region: us-south
   zone: dal10
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 20Gi
 storageClassName: ibmc-block-silver
